name: CI Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven (skip Selenium)
        run: mvn -B clean install -DexcludeTests="**/selenium/**"

      - name: Run Unit & API Tests (skip Selenium)
        run: mvn test -DexcludeTests="**/selenium/**"
        env:
          SPRING_PROFILES_ACTIVE: test
          MONGO_URI: mongodb+srv://janidu:janidu2001@cluster0.zgp4c9w.mongodb.net/MoviesDB
