name: CI Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Install Chrome and ChromeDriver using GitHub Action
      - name: Setup Chrome and ChromeDriver
        uses: nanasess/setup-chrome@v1
        with:
          chrome-version: latest
          chromedriver-version: latest

      # Build with Maven (inside backend folder)
      - name: Build with Maven
        working-directory: LuxReelProject/Backend/LuxReel
        run: mvn -B clean install

      # Run Unit & Selenium Tests
      - name: Run Unit & Selenium Tests
        working-directory: LuxReelProject/Backend/LuxReel
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test
          MONGO_URI: mongodb+srv://janidu:janidu2001@cluster0.zgp4c9w.mongodb.net/MoviesDB
